name: Sync Fork

on:
  schedule:
    - cron: '0 7 */2 * *' # every month
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2.0.10
        with:
          auto_approve: true
          merge_method: rebase
          pr_title: 同步源仓库
          ignore_fail: true
          token: ${{ secrets.SYNC_TOKEN }}
          owner: ChatGPTNextWeb
          repo: NextChat
          base: main
          head: main
